openapi: 3.0.3
info:
  title: Product Service API
  version: 1.0.3
  description: API для управления товарами.
servers:
  - url: http://localhost:8080/api/v1
    description: Локальный сервер Product Service
paths:
  /products:
    get:
      summary: Получение списка товаров
      operationId: getProducts
      parameters:
        # Пагинация
        - name: page
          in: query
          required: false
          description: Номер страницы (с 0)
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          required: false
          description: Размер страницы (макс. 100)
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20

        # Сортировка
        - name: sort
          in: query
          required: false
          description: Поле сортировки
          schema:
            type: string
            enum: [ name, price, createdAt, updatedAt ]
            default: createdAt
        - name: direction
          in: query
          required: false
          description: Направление сортировки
          schema:
            type: string
            enum: [ asc, desc ]
            default: desc

        # Фильтрация
        - name: name
          in: query
          required: false
          description: Фильтрация по названию (без учета регистра)
          schema:
            type: string
        - name: category
          in: query
          required: false
          description: Фильтрация по категории
          schema:
            type: string
        - name: status
          in: query
          required: false
          description: Фильтрация по статусу
          schema:
            $ref: '#/components/schemas/ProductStatus'
        - name: minPrice
          in: query
          required: false
          description: Фильтрация по цене
          schema:
            type: number
            minimum: 0
        - name: maxPrice
          in: query
          required: false
          description: Фильтрация по цене
          schema:
            type: number
            minimum: 0
      responses:
        '200':
          description: Успешный ответ с информацией о товарах
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsPageResponse'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Конфликт данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /products/{id}:
    get:
      summary: Получение товара по ID
      operationId: getProductById
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор товара (UUID)
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Успешный ответ с информацией о товаре
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Конфликт данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Удаление товара по ID
      operationId: deleteProductById
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор товара (UUID)
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Товар успешно удален
        '400':
          description: Некорректный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Конфликт данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products/{id}/status:
    patch:
      summary: Изменение статуса товара
      operationId: updateProductStatus
      parameters:
        - name: id
          in: path
          required: true
          description: Уникальный идентификатор товара (UUID)
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductStatusRequest'
      responses:
        '200':
          description: Статус обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateProductStatusResponse'
        '404':
          description: Товар не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Конфликт данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ProductDto:
      type: object
      required:
        - id
        - name
        - price
        - currency
        - status
        - createdAt
        - updatedAt
        - version
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор товара
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        name:
          type: string
          description: Название товара
          example: "MacBook Pro 14"
          nullable: false
        description:
          type: string
          description: Описание товара
          example: "Laptop Apple MacBook Pro"
        category:
          type: string
          description: Категория товара
          example: "LAPTOP"
        price:
          type: number
          description: Цена
          example: 1250.50
          nullable: false
        currency:
          type: string
          description: Валюта
          example: "EUR"
          nullable: false
        status:
          $ref: '#/components/schemas/ProductStatus'
        createdAt:
          type: string
          format: date-time
          description: Дата создания
          example: "2023-10-27T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Дата последнего изменения
          example: "2023-10-27T10:30:00Z"
        version:
          type: integer
          format: int64
          description: Версия сущности
          example: 2

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2023-10-27T10:00:00Z"
        status:
          type: integer
          example: 404
        error:
          type: string
          example: "PRODUCT_NOT_FOUND"
        message:
          type: string
          example: "Product with id 3c16946e-d1a8-46b3-8c45-220c43283284 not found"
        path:
          type: string
          example: "/api/v1/products/3c16946e-d1a8-46b3-8c45-220c43283284"

    UpdateProductStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/ProductStatus'

    ProductsPageResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ProductDto'
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 20
        totalElements:
          type: integer
          example: 105
        totalPages:
          type: integer
          example: 5
        first:
          type: boolean
          example: true
        last:
          type: boolean
          example: false
    UpdateProductStatusResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/ProductStatus'
    ProductStatus:
      type: string
      enum: [ ACTIVE, INACTIVE, OUT_OF_STOCK ]
      description: Статус товара
      nullable: false


    ProductEvent:
      type: object
      required:
        - id
        - eventType
        - eventVersion
        - eventTimestamp
        - product
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор события
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
          nullable: false
        eventType:
          $ref: '#/components/schemas/ProductEventType'
        eventVersion:
          type: integer
          format: int64
          description: Версия события
          example: 2
        eventTimestamp:
          type: string
          format: date-time
          description: Дата события
          example: "2023-10-27T10:00:00Z"
        product:
          $ref: '#/components/schemas/ProductEventPayload'

    ProductEventType:
      type: string
      enum:
        - PRODUCT_CREATED
        - PRODUCT_UPDATED
      description: Тип события

    ProductEventPayload:
      type: object
      required:
        - id
        - name
        - price
        - currency
        - status
        - version
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор товара
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        name:
          type: string
          description: Название товара
          example: "MacBook Pro 14"
          nullable: false
        description:
          type: string
          description: Описание товара
          example: "Laptop Apple MacBook Pro"
        category:
          type: string
          description: Категория товара
          example: "LAPTOP"
        price:
          type: number
          description: Цена
          example: 1250.50
          nullable: false
        currency:
          type: string
          description: Валюта
          example: "EUR"
          nullable: false
        status:
          $ref: '#/components/schemas/ProductStatus'
        version:
          type: integer
          format: int64
          description: Версия сущности
          example: 2
