spring:
  profiles:
    active: dev

  application:
    name: productservice

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/product_service}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:postgres}
#    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000