spring:
  profiles:
    active: dev

  application:
    name: productservice

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  datasource:
#    url: ${DB_URL:jdbc:postgresql://localhost:5432/product_service}
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:postgres}
#    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
app:
  kafka:
    log-payload: true
  product-consumer-properties:
    enabled: true
    topic: "product-events"
    group-id: "product-service"
    consumer-count: 3
    consumer-max-poll-records: 500
    retry-back-off: 2000
    retry-attempts: 3
    dlt-topic-name: ${app.product-consumer-properties.topic}.DLT
    dlt-partitions: 3
    dlt-replicas: 1
  infra:
    kafka:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}


